#!/bin/bash
# =============================================================================
# Generate Jenkins .env from Terraform Outputs
# =============================================================================
# This script reads `terraform output -json jenkins_credentials` from the MAIN
# terraform workspace (Multi_Container_App/terraform/) and writes the values
# into docker_jenkins/.env for Jenkins JCasC to consume.
#
# Usage:
#   cd Multi_Container_App/docker_jenkins
#   ./generate-jenkins-env.sh
#
# Prerequisites:
#   - jq installed
#   - terraform CLI installed
#   - Main terraform state is current (run terraform apply first)
# =============================================================================

set -euo pipefail

# ---------- Paths ----------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TERRAFORM_DIR="$(cd "$SCRIPT_DIR/../terraform" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

echo "=== Generating Jenkins .env from Terraform outputs ==="
echo ">>> Terraform directory: $TERRAFORM_DIR"
echo ">>> Output file: $ENV_FILE"

# ---------- Validate prerequisites ----------
if ! command -v jq &> /dev/null; then
  echo "ERROR: jq is required but not installed. Install it with: sudo apt-get install jq"
  exit 1
fi

if ! command -v terraform &> /dev/null; then
  echo "ERROR: terraform is required but not installed."
  exit 1
fi

# ---------- Read terraform outputs ----------
echo ">>> Reading terraform outputs..."
CREDS_JSON=$(cd "$TERRAFORM_DIR" && terraform output -json jenkins_credentials)

# Helper to extract a value from the JSON
get_val() {
  echo "$CREDS_JSON" | jq -r ".$1 // empty"
}

# ---------- Individual outputs (not nested in jenkins_credentials) ----------
ECR_REGISTRY=$(cd "$TERRAFORM_DIR" && terraform output -raw jenkins_ecr_registry 2>/dev/null || echo "")
EC2_HOST=$(cd "$TERRAFORM_DIR" && terraform output -raw instance_public_ip 2>/dev/null || echo "")
SSH_KEY=$(cd "$TERRAFORM_DIR" && terraform output -raw jenkins_ec2_ssh_key 2>/dev/null || echo "")
ECS_ALB_DNS=$(cd "$TERRAFORM_DIR" && terraform output -raw ecs_alb_dns_name 2>/dev/null || echo "")
ECS_CLUSTER=$(cd "$TERRAFORM_DIR" && terraform output -raw ecs_cluster_name 2>/dev/null || echo "")
ECS_SERVICE=$(cd "$TERRAFORM_DIR" && terraform output -raw ecs_service_name 2>/dev/null || echo "")
ECS_EXEC_ROLE=$(cd "$TERRAFORM_DIR" && terraform output -raw ecs_task_execution_role_arn 2>/dev/null || echo "")
ECS_TASK_ROLE=$(cd "$TERRAFORM_DIR" && terraform output -raw ecs_task_role_arn 2>/dev/null || echo "")
CODEDEPLOY_APP=$(cd "$TERRAFORM_DIR" && terraform output -raw codedeploy_app_name 2>/dev/null || echo "")
CODEDEPLOY_DG=$(cd "$TERRAFORM_DIR" && terraform output -raw codedeploy_deployment_group 2>/dev/null || echo "")
MONITORING_IP=$(cd "$TERRAFORM_DIR" && terraform output -raw monitoring_server_ip 2>/dev/null || echo "")

# ---------- Values from jenkins_credentials JSON ----------
AWS_REGION=$(get_val "aws_region")
DB_USERNAME=$(get_val "db_username")
DB_PASSWORD=$(get_val "db_password")
DB_NAME=$(get_val "db_name")
SONAR_TOKEN=$(get_val "sonarcloud_token")
SLACK_TOKEN=$(get_val "slack_token")

# Use individual outputs as fallback over jenkins_credentials
ECR_REGISTRY="${ECR_REGISTRY:-$(get_val 'ecr_registry')}"
EC2_HOST="${EC2_HOST:-$(get_val 'ec2_host')}"
SSH_KEY="${SSH_KEY:-$(get_val 'ec2_ssh_private_key')}"
ECS_ALB_DNS="${ECS_ALB_DNS:-$(get_val 'ecs_alb_dns_name')}"
CODEDEPLOY_APP="${CODEDEPLOY_APP:-$(get_val 'codedeploy_app_name')}"
CODEDEPLOY_DG="${CODEDEPLOY_DG:-$(get_val 'codedeploy_deployment_group')}"
ECS_EXEC_ROLE="${ECS_EXEC_ROLE:-$(get_val 'ecs_task_execution_role_arn')}"
ECS_TASK_ROLE="${ECS_TASK_ROLE:-$(get_val 'ecs_task_role_arn')}"

# Build OTEL endpoint from monitoring server IP
OTEL_ENDPOINT=""
if [ -n "$MONITORING_IP" ]; then
  OTEL_ENDPOINT="http://${MONITORING_IP}:4318/v1/traces"
fi

# ---------- Prompt for AWS Credentials ----------
echo ""
echo ">>> Jenkins requires AWS credentials for ECR and ECS deployments."
read -p "Enter AWS Access Key ID: " AWS_ACCESS_KEY_ID
read -s -p "Enter AWS Secret Access Key: " AWS_SECRET_ACCESS_KEY
echo ""

TFVARS_FILE="$SCRIPT_DIR/../terraform_jenkins/jenkins.auto.tfvars"

# ---------- Write .tfvars ----------
echo ">>> Writing Jenkins variables to $TFVARS_FILE..."
cat > "$TFVARS_FILE" << EOF
# =============================================================================
# Jenkins Credentials — Auto-generated by generate-jenkins-env.sh
# Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# =============================================================================

jenkins_admin_user            = "admin"
jenkins_admin_password        = "admin"

jenkins_aws_access_key_id     = "${AWS_ACCESS_KEY_ID}"
jenkins_aws_secret_access_key = "${AWS_SECRET_ACCESS_KEY}"
jenkins_ecr_registry          = "${ECR_REGISTRY}"
jenkins_ec2_host              = "${EC2_HOST}"

# SSH Key is multiline, so we use HCL heredoc syntax
jenkins_ec2_ssh_key = <<-EOT
${SSH_KEY}
EOT

jenkins_db_username           = "${DB_USERNAME}"
jenkins_db_password           = "${DB_PASSWORD}"
jenkins_db_name               = "${DB_NAME}"
jenkins_sonar_token           = "${SONAR_TOKEN}"
jenkins_slack_token           = "${SLACK_TOKEN}"
jenkins_codedeploy_app        = "${CODEDEPLOY_APP}"
jenkins_codedeploy_dg         = "${CODEDEPLOY_DG}"
jenkins_ecs_alb_dns           = "${ECS_ALB_DNS}"
jenkins_ecs_cluster           = "${ECS_CLUSTER}"
jenkins_ecs_service           = "${ECS_SERVICE}"
jenkins_ecs_exec_role         = "${ECS_EXEC_ROLE}"
jenkins_ecs_task_role         = "${ECS_TASK_ROLE}"
jenkins_otel_endpoint         = "${OTEL_ENDPOINT}"
EOF

echo ""
echo "=== jenkins.auto.tfvars generated successfully ==="
echo ""
echo ">>> TRUE AUTOMATION DEPLOYMENT COMPLETE:"
echo ">>>   All credentials and configuration files will now be injected into"
echo ">>>   the Jenkins EC2 instance automatically via Terraform user_data."
echo ""
echo ">>> NEXT STEPS:"
echo ">>>   cd ../terraform_jenkins"
echo ">>>   terraform init"
echo ">>>   terraform apply"
echo ""
